name: Release Workflow
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_GITHUB_KEY }}
          DOCKER_REGISTRY_URL: "docker.pkg.github.com"
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY_URL}

      - name: Set version env
        run: echo "::set-env name=GIT_TAG::${GITHUB_REF#refs/*/}"

      - name: Build Docker container
        run: docker build -f build/Dockerfile -t docker.pkg.github.com/kudobuilder/kitt/kitt:$GIT_TAG .

      - name: Push Docker container
        run: docker push docker.pkg.github.com/kudobuilder/kitt/kitt:$GIT_TAG
