name: Release Workflow
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Github Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: build/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kudobuilder/kitt/kitt
          tag_with_ref: true
